# Generated by Django 4.2.7 on 2024-04-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=100, verbose_name='Division')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='TrainedPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(choices=[('people_trained', 'No. of People Trained'), ('manhours', 'Manhours')], max_length=20)),
                ('onroll_male', models.IntegerField(default=0, verbose_name='Onroll - Male')),
                ('onroll_female', models.IntegerField(default=0, verbose_name='Onroll - Female')),
                ('offroll_male', models.IntegerField(default=0, verbose_name='Off roll - Male')),
                ('offroll_female', models.IntegerField(default=0, verbose_name='Off roll - Female')),
            ],
            options={
                'verbose_name': 'Training Data',
                'verbose_name_plural': 'Training Data',
            },
        ),
    ]
