# Generated by Django 4.2.7 on 2024-04-23 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0002_employeedata_trainedpeople'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopletrained',
            old_name='permanent_female_count',
            new_name='onroll_female',
        ),
        migrations.RenameField(
            model_name='peopletrained',
            old_name='permanent_male_count',
            new_name='onroll_female_pt',
        ),
        migrations.RenameField(
            model_name='peopletrained',
            old_name='temporary_female_count',
            new_name='onroll_male',
        ),
        migrations.RenameField(
            model_name='peopletrained',
            old_name='temporary_male_count',
            new_name='onroll_male_pt',
        ),
    ]
