# Generated by Django 4.2.7 on 2024-04-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0005_alter_peopletrained_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopletrained',
            old_name='offroll_female_pt',
            new_name='permanentfemale',
        ),
        migrations.RenameField(
            model_name='peopletrained',
            old_name='offroll_male',
            new_name='permanentmale',
        ),
        migrations.RenameField(
            model_name='peopletrained',
            old_name='onroll_female',
            new_name='tempfemale',
        ),
        migrations.RenameField(
            model_name='peopletrained',
            old_name='onroll_male_pt',
            new_name='tempmale',
        ),
    ]
