# Generated by Django 4.2.7 on 2024-04-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0007_alter_trainedpeople_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(choices=[('Near miss', 'Near miss'), ('First aid cases', 'First aid cases'), ('Medically treated Injuries (MTI )', 'Medically treated Injuries (MTI )'), (' Restricted Work Case ( RWC)', ' Restricted Work Case ( RWC)'), ('Lost time or reportable Injuries (LTI )', 'Lost time or reportable Injuries (LTI )'), ('Man Power strength', 'Man Power strength')], max_length=100)),
                ('onroll_com', models.IntegerField(default=0, verbose_name='Onroll - com')),
                ('offroll_com', models.IntegerField(default=0, verbose_name='Off roll - com')),
            ],
        ),
        migrations.AlterModelOptions(
            name='trainedpeople',
            options={},
        ),
        migrations.AlterField(
            model_name='trainedpeople',
            name='form_name',
            field=models.CharField(choices=[('people_trained', 'No. of People Trained'), ('manhours', 'Manhours')], max_length=20),
        ),
    ]
