# Generated by Django 4.2.7 on 2024-04-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0008_commonone_alter_trainedpeople_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements_For_the_Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievements_Forthe_Month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Major', models.IntegerField(default=0)),
                ('Minor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Manhours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('permanentmale_mh', models.IntegerField(default=0)),
                ('permanentfemale_mh', models.IntegerField(default=0)),
                ('tempmale_mh', models.IntegerField(default=0)),
                ('tempfemale_mh', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noof_EventMP_approved_and_issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_EventMP_approved_and_issued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noof_MOCs_approved_and_issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_MOCs_approved_and_issued', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noof_observations_Action_taken_ytd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_observations_Action_taken_ytd', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noof_observations_for_the_month_by_walk_throughexternal_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noof_observations_for_the_month_by_walk_through_external_audit', models.ImageField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Noof_observations_for_themonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noof_observations_for_the_month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noof_observations_pending_ytd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_observations_pending_ytd', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noof_Road_Realated_Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoofRoadRealatedIncidents', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noof_Safety_Inspections_Carriedoutin_Plants_Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoofSafetyInspectionsCarriedoutinPlantsRetail', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Noofsafetyalertcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken_ytd', models.IntegerField(default=0)),
                ('pending_ytd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noofsafetyalertcardreceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onroll_sacr', models.IntegerField(default=0)),
                ('offroll_sacr', models.IntegerField(default=0)),
                ('Cumulative_yt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NumberofTrainingSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberofTrainingSessions', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_for_the_Next_Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_forthe_Next_Month', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Total_Noof_observations_ytd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_No_of_observations_ytd', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TrainedPeople',
        ),
    ]
