# Generated by Django 4.2.7 on 2024-04-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0010_work_permit_issued_alter_commonone_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberoftrainingsessions',
            old_name='NumberofTrainingSessions',
            new_name='NumberofTrainingsessions',
        ),
    ]
