# Generated by Django 4.2.7 on 2024-04-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0011_rename_numberoftrainingsessions_numberoftrainingsessions_numberoftrainingsessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements_for_the_month',
            name='Achievements_Forthe_Month',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commonone',
            name='offroll_com',
            field=models.IntegerField(blank=0, default=0, null=True, verbose_name='Off roll - com'),
        ),
        migrations.AlterField(
            model_name='commonone',
            name='onroll_com',
            field=models.IntegerField(blank=0, default=0, null=True, verbose_name='Onroll - com'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='Major',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='Minor',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='permanentfemale_mh',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='permanentmale_mh',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='tempfemale_mh',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manhours',
            name='tempmale_mh',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noof_eventmp_approved_and_issued',
            name='No_of_EventMP_approved_and_issued',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noof_mocs_approved_and_issued',
            name='No_of_MOCs_approved_and_issued',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noof_observations_action_taken_ytd',
            name='No_of_observations_Action_taken_ytd',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noof_observations_for_the_month_by_walk_throughexternal_audit',
            name='Noof_observations_for_the_month_by_walk_through_external_audit',
            field=models.ImageField(blank=0, default=0, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noof_observations_for_themonth',
            name='Noof_observations_for_the_month',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noof_observations_pending_ytd',
            name='No_of_observations_pending_ytd',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noof_road_realated_incidents',
            name='NoofRoadRealatedIncidents',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noof_safety_inspections_carriedoutin_plants_retail',
            name='NoofSafetyInspectionsCarriedoutinPlantsRetail',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noofsafetyalertcard',
            name='action_taken_ytd',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noofsafetyalertcardreceived',
            name='offroll_sacr',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='noofsafetyalertcardreceived',
            name='onroll_sacr',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peopletrained',
            name='permanentfemale',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peopletrained',
            name='permanentmale',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peopletrained',
            name='tempfemale',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peopletrained',
            name='tempmale',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plan_for_the_next_month',
            name='Plan_forthe_Next_Month',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='total_noof_observations_ytd',
            name='Total_No_of_observations_ytd',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='work_permit_issued',
            name='work_permit_issue',
            field=models.IntegerField(blank=0, default=0, null=True),
        ),
    ]
