# Generated by Django 4.2.7 on 2024-04-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0013_alter_commonone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Aid_cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onroll_fa', models.IntegerField(blank=True, default=0, null=True)),
                ('offroll_fa', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onroll_lti', models.IntegerField(blank=True, default=0, null=True)),
                ('offroll_lti', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onroll_mp', models.IntegerField(blank=True, default=0, null=True)),
                ('offroll_mp', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onroll_mti', models.IntegerField(blank=True, default=0, null=True)),
                ('offroll_mti', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nearmiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onroll_nm', models.IntegerField(blank=True, default=0, null=True)),
                ('offroll_nm', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RWC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onroll_rwc', models.IntegerField(blank=True, default=0, null=True)),
                ('offroll_rwc', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CommonOne',
        ),
    ]
