# Generated by Django 4.2.7 on 2024-05-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0016_alter_peopletrained_achievements_forthe_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopletrained',
            name='emp_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
