# Generated by Django 4.2.7 on 2024-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0018_peopletrained_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopletrained',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
