# Generated by Django 4.2.7 on 2024-05-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0021_rename_table_field_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title_creation',
            old_name='table_name',
            new_name='fields',
        ),
        migrations.RenameField(
            model_name='title_creation',
            old_name='field2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='field_creation',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='field_creation',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='title_creation',
            name='field1',
        ),
        migrations.AddField(
            model_name='field_creation',
            name='field',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
