# Generated by Django 4.2.7 on 2024-05-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0022_rename_table_name_title_creation_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title_creation',
            name='fields',
        ),
        migrations.AddField(
            model_name='title_creation',
            name='fields',
            field=models.ManyToManyField(to='mis_dash.field_creation'),
        ),
    ]
