# Generated by Django 4.2.7 on 2024-05-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0023_remove_title_creation_fields_title_creation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='table_names',
        ),
        migrations.AddField(
            model_name='location',
            name='Division',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='Title_Creation_names',
            field=models.ManyToManyField(to='mis_dash.title_creation'),
        ),
    ]
