# Generated by Django 4.2.7 on 2024-05-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0025_alter_field_creation_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title_creation',
            name='title',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
