# Generated by Django 4.2.7 on 2024-05-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0026_alter_title_creation_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicInputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=100)),
            ],
        ),
    ]
