# Generated by Django 4.2.7 on 2024-05-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0027_dynamicinputmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30)),
                ('field_value', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_dash.location')),
                ('title_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_dash.title_creation')),
            ],
        ),
        migrations.DeleteModel(
            name='DynamicInputModel',
        ),
    ]
