# Generated by Django 4.2.7 on 2024-05-10 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0029_rename_fields_title_creation_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdataentry',
            name='title_creation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mis_dash.title_creation'),
        ),
    ]
