# Generated by Django 4.2.7 on 2024-05-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0030_alter_formdataentry_title_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdataentry',
            name='title_creation',
        ),
    ]
