# Generated by Django 4.2.7 on 2024-05-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0031_remove_formdataentry_title_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdataentry',
            name='location',
        ),
    ]
