# Generated by Django 4.2.7 on 2024-05-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0032_remove_formdataentry_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDataEntry',
        ),
    ]
