# Generated by Django 4.2.7 on 2024-05-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0036_formdata_empid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeopleTrained',
        ),
    ]
