# Generated by Django 4.2.7 on 2024-05-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0037_delete_peopletrained'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean_dict', models.JSONField(default=dict)),
                ('locations', models.CharField(max_length=50)),
            ],
        ),
    ]
