# Generated by Django 4.2.7 on 2024-05-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0038_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='boolean_dict',
        ),
        migrations.AddField(
            model_name='show',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mis_dash.title_creation'),
            preserve_default=False,
        ),
    ]
