# Generated by Django 4.2.7 on 2024-05-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0039_remove_show_boolean_dict_show_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='list',
        ),
        migrations.AddField(
            model_name='show',
            name='list',
            field=models.ManyToManyField(to='mis_dash.title_creation'),
        ),
    ]
