# Generated by Django 4.2.7 on 2024-05-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0040_remove_show_list_show_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='divisions',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
