# Generated by Django 4.2.7 on 2024-05-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0042_approvalnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='division',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdata',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
