# Generated by Django 4.2.7 on 2024-05-14 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0043_formdata_division_formdata_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
