# Generated by Django 4.2.7 on 2024-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0044_formdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='edit',
            field=models.BooleanField(default=True),
        ),
    ]
