# Generated by Django 4.2.7 on 2024-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0045_formdata_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20)),
                ('edit', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='formdata',
            unique_together={('field_name', 'title_creation')},
        ),
    ]
