# Generated by Django 4.2.7 on 2024-05-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0046_edit_alter_formdata_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMas',
            fields=[
                ('s_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('approval_request_raised_by', models.CharField(max_length=255)),
                ('request_status', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='edit',
        ),
    ]
