# Generated by Django 4.2.7 on 2024-05-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0047_usermas_delete_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_forthe_Next_Month', models.CharField(default='0', max_length=255)),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('remarks', models.TextField(blank=True, default='0')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
