# Generated by Django 4.2.7 on 2024-05-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0049_attachment_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='empid',
        ),
    ]
