# Generated by Django 4.2.7 on 2024-05-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0050_remove_attachment_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='empid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
